name: WordHunt

services:
  wordhunt:
    container_name: wordhunt
    image: wordhunt:latest
    ports:
      - "5000:5000"
    networks:
      - wordhunt-network
    restart: unless-stopped
    
networks:
  wordhunt-network:
    driver: bridge
